name: 'Upload Coverage Artifact'
description: 'Upload coverage report as build artifact'
inputs:
  name:
    description: 'Artifact name'
    required: false
    default: 'coverage-report'
  retention-days:
    description: 'Number of days to retain artifact'
    required: false
    default: '7'

runs:
  using: 'composite'
  steps:
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.name }}
        path: |
          coverage/
          !coverage/tmp/
        retention-days: ${{ inputs.retention-days }}
        if-no-files-found: warn